### PR TITLE
The Brand LOGO design was added !!

### PR DESCRIPTION
**Pull request by Nishith-Gohel**
I had designed The Lean Programmer LOGO using the UI/UX tool figma, whose converted PNG file is attached here with, hope it meets your requirements.

### CODE REVIEW

**Comment by Nishith-Gohel** [comment]
@MadhavBahl , I had made the PR, a couple of weeks before, and hasn't still been reviewed under Hacktoberfest 2021. Could you just at once acknowledge whether you had a look at the work done, and if so then could you merge the PR to main and add the "hacktoberfest-accepted" label to the PR.
It would be good if you respond to the messages and review the work done @MadhavBahl .

**Comment by MadhavBahl** [comment]
Hey @Nishith-Gohel , sorry, I was a little inactive from past couple of weeks due to other commitments, checking your PR

**Review by MadhavBahl — COMMENTED** [review]
@Nishith-Gohel , thanks a lot for giving it a try, but this has a lot of text and images, it'd be great if we had a minimal logo

Although, I appreciate you for the efforts in contribution, I will merge this - can you rename the file to - `LogoByNishith` - and I will accept it so that it counts a valid contribution.

I'll see if I can modify and re-use this

**Comment by Nishith-Gohel** [comment]
Sure, I shall rename it.

**Pull request closed without merging**
