### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by vinird**
Hi, hope you enjoy this logo!

### CODE REVIEW

**Comment by MadhavBahl** [comment]
Hey @vinird the logo is super awesomeee ❤️ 
Amazing work 🌟 

Although I have a request, can you try replacing the glasses by mustache? or something else?

**Comment by MadhavBahl** [comment]
I mean, instead of glasses, you can put mustache above lips or something like that

**Comment by vinird** [comment]
Sure! Pick one 
https://www.baldingbeards.com/wp-content/uploads/2017/02/mustache-styles-chart.jpg

**Comment by MadhavBahl** [comment]
Can you try with 
1. English Mustache. and
2. The Gunslinger?

image

image

**Comment by vinird** [comment]
Ok, gonna send two proposals!

**Comment by vinird** [comment]
@MadhavBahlMD I like the English one!

**Comment by MadhavBahl** [comment]
Amazing @vinird 😃 

Yes, english looks better 💯 

Merging the PR

**Pull request merged**
