### PR TITLE
logo added

### PR DESCRIPTION
**Pull request by reallinfo**

### CODE REVIEW

**Comment by MadhavBahl** [comment]
Amazing @reallinfo 💯 

The logo is super awesomee 🌟 

Merging the PR, will add the license and contributors list soon

**Comment by reallinfo** [comment]
You're welcome Madhav. Goodworks!

**Comment by MadhavBahl** [comment]
@reallinfo added you in contributors list in README.md, will go through the MIT license and add it soon 😃

**Comment by reallinfo** [comment]
wow, looks so pretty! :D Thank you so much.

**Pull request merged**
